### ISSUE TITLE
test failure because of a stack-buffer-overflow

### ISSUE THREAD

**Issue by asarubbo** [pwsafe/pwsafe#1027]
Our [Gentoo Tinderbox](https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/) reported a test failure at [bug 914185](https://bugs.gentoo.org/914185)

By looking at LastTest.log I can see:

```
==44==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd132045e0 at pc 0x565339fbbd4e bp 0x7ffd132043f0 sp 0x7ffd13203bb8
READ of size 352 at 0x7ffd132045e0 thread T0
    #0 0x565339fbbd4d in wcslen (/var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0_build/src/test/coretest+0x106d4d)
    #1 0x56533a2684a5 in std::char_traits<wchar_t>::length(wchar_t const*) /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/char_traits.h:540:9
    #2 0x56533a2684a5 in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t>>::assign(wchar_t const*) /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/basic_string.h:1673:6
    #3 0x56533a2684a5 in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t>>::operator=(wchar_t const*) /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/basic_string.h:812:22
    #4 0x56533a2684a5 in PWSUtil::ConvertToDateTimeString[abi:cxx11](long const&, PWSUtil::TMC) /var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0/src/core/Util.cpp:531:9
    #5 0x56533a192fd1 in CreatePWHistoryList(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, S_Alloc::SecureAlloc<wchar_t>> const&, unsigned long&, unsigned long&, std::vector<PWHistEntry, std::allocator<PWHistEntry>>&, PWSUtil::TMC) /var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0/src/core/PWHistory.cpp:111:7
    #6 0x56533a08b0fd in ItemDataTest_PasswordHistory_Test::TestBody() /var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0/src/test/ItemDataTest.cpp:185:3
    #7 0x7f4cfdf0c8a6 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/usr/lib64/libgtest.so.1.14.0+0x5c8a6)
    #8 0x7f4cfdef3e4d in testing::Test::Run() (/usr/lib64/libgtest.so.1.14.0+0x43e4d)
    #9 0x7f4cfdef4004 in testing::TestInfo::Run() (/usr/lib64/libgtest.so.1.14.0+0x44004)
    #10 0x7f4cfdef41ee in testing::TestSuite::Run() (/usr/lib64/libgtest.so.1.14.0+0x441ee)
    #11 0x7f4cfdf0174b in testing::internal::UnitTestImpl::RunAllTests() (/usr/lib64/libgtest.so.1.14.0+0x5174b)
    #12 0x7f4cfdf0cf36 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/usr/lib64/libgtest.so.1.14.0+0x5cf36)
    #13 0x7f4cfdef43e3 in testing::UnitTest::Run() (/usr/lib64/libgtest.so.1.14.0+0x443e3)
    #14 0x56533a0dacb3 in RUN_ALL_TESTS() /usr/include/gtest/gtest.h:2317:73
    #15 0x56533a0dacb3 in main /var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0/src/test/coretest.cpp:30:12
    #16 0x7f4cfce23c89  (/lib64/libc.so.6+0x23c89)
    #17 0x7f4cfce23d44 in __libc_start_main (/lib64/libc.so.6+0x23d44)
    #18 0x565339f54030 in _start (/var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0_build/src/test/coretest+0x9f030)

Address 0x7ffd132045e0 is located in stack of thread T0 at offset 416 in frame
    #0 0x56533a2680cf in PWSUtil::ConvertToDateTimeString[abi:cxx11](long const&, PWSUtil::TMC) /var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0/src/core/Util.cpp:499

  This frame has 5 object(s):
    [32, 64) 'ret' (line 500)
    [96, 416) 'datetime_str' (line 502)
    [480, 536) 'st_s' (line 504) <== Memory access at offset 416 partially underflows this variable
    [576, 584) 'ref.tmp' (line 508) <== Memory access at offset 416 partially underflows this variable
    [608, 616) 'ref.tmp20' (line 529) <== Memory access at offset 416 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/var/tmp/portage/app-admin/passwordsafe-1.17.0/work/pwsafe-1.17.0_build/src/test/coretest+0x106d4d) in wcslen
Shadow bytes around the buggy address:
  0x7ffd13204300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffd13204380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffd13204400: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 00
  0x7ffd13204480: f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffd13204500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7ffd13204580: 00 00 00 00 00 00 00 00 00 00 00 00[f2]f2 f2 f2
  0x7ffd13204600: f2 f2 f2 f2 00 00 00 00 00 00 00 f2 f2 f2 f2 f2
  0x7ffd13204680: f8 f2 f2 f2 f8 f3 f3 f3 00 00 00 00 00 00 00 00
  0x7ffd13204700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffd13204780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffd13204800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==44==ABORTING
```

I didn't look deeply into this issue so I don't know if the bug is in the unittest itself or in the involed libraries/daemons, if so please check for any security implications.
If I can do further, please let me know.

**Comment by ronys** [comment]
Thanks for the bug report.
The test in question is in mature code that's been ported and tested on many platforms, so I'd be more inclined to suspect the environment (compiler, libraries). Is there any way for me to dive into this without creating a Gentoo VM?

**Comment by asarubbo** [comment]
Hi,

I don't think it is anything Gentoo-specific. You should see the bug in a normal way if you run the specified test under `valgrind` or if you want to reproduce the same output you should compile with `-fsanitize=address`
